### PR TITLE
fixed some typos in LISY readme files

### PR DESCRIPTION
**Pull request by mkalkbrenner**

### CODE REVIEW

**Comment by toxieainc** [comment]
Thanks! Although i don't know if the 'HOme' spelling variant is actually intentional for whatever reason.

**Comment by mkalkbrenner** [comment]
@bontango I think the official name is LISY_Home, right?

**Comment by toxieainc** [comment]
Also true.. ..

**Comment by bontango** [comment]
thx for corrections, and yes it is 'LISY_Home' or 'LISY_H'
btw. in the readme you mentioned Atari support with LISY. 
This is (still) planed, but not implemented yet.

**Comment by toxieainc** [comment]
@bontango : All the lisy files are more or less a 1:1 copy of your fork, see https://github.com/bontango/lisy-src-5.x/blob/master/src/lisy/README.lisy#L1 , so the Atari part is coming from you directly.  ;)
I just always tried to keep everything up to date in 'our' copy, as obviously PinMAME still continues to have changes in GTS/S11/etc, but your fork is based on a fixed version.

**Pull request merged**
