### PR TITLE
PWM: improve MODSOL implementation

### PR DESCRIPTION
**Pull request by vbousquet**
- Core: Don't write lamp matrix PWM if not enabled
- Core: Fix integration not being done up to 'now'
- WPC: only write PWM data corresponding to the options
- also minor formating cleanups

Should improve https://github.com/vpinball/pinmame/issues/266 and https://github.com/vpinball/pinmame/issues/268

### CODE REVIEW

**Comment by toxieainc** [comment]
Thanks!
But the part with 'now' is kinda fishy to me now. I did it like that to be able to make the integration more even/'smooth', i.e. with roughly same-length segments over which the PWM is integrated then. Otherwise one gets screw ups in the values, especially if its in a flicker fusion 'phase'.
Or was there some noticeable issue with some tables/machines with my code?

**Comment by vbousquet** [comment]
I may not have understood the intent regarding the 'now' part. When I reviewed the code, it looked wrong to me because I think it would lead to integration of the wrong output value. Here is the original code:
```
  const float U = (((coreGlobals.binaryOutputState[index >> 3] >> (index & 7)) & 1) ^ output->state.bulb.isReversed) ? output->state.bulb.U : 0.f;
  const float dt_diff = (float)(output->state.bulb.integrationTimestamp - output->state.bulb.prevIntegrationTimestamp);

  if(U != output->state.bulb.prevIntegrationValue        // state flip?
     || dt_diff >= (float)(BULB_INTEGRATION_PERIOD*20.)) // or we waited long enough to get a stable discrete integration
  {
    // do the integration in a loop of small steps, roughly in BULB_INTEGRATION_PERIOD sized steps (but rounded up/down to have same sized cycles in here)
    float countf = floorf(dt_diff*(float)(1./BULB_INTEGRATION_PERIOD) + 0.5f);
    if(countf < 1.f) // single cycle/short pulses need to use the 'original' cycle time as a workaround
      countf = 1.f;
    const int count = (int)countf;
    const float dt = dt_diff/countf;
    for(int i = 0; i < count; ++i) {
      // Keeps T within the range of the LUT (between room temperature and melt down point)
      output->state.bulb.filament_temperature = output->state.bulb.filament_temperature < 293.0f ? 293.0f : output->state.bulb.filament_temperature > (float) BULB_T_MAX ? (float) BULB_T_MAX : output->state.bulb.filament_temperature;
      const float Ut = output->state.bulb.isAC ? (1.41421356f * sinf((float)(60.0 * 2.0 * PI) * (float)(output->state.bulb.prevIntegrationTimestamp - coreGlobals.lastACZeroCrossTimeStamp)) * output->state.bulb.prevIntegrationValue) : output->state.bulb.prevIntegrationValue;
      const float dT = dt * (float)bulb_heat_up_factor(output->state.bulb.bulb, output->state.bulb.filament_temperature, Ut, output->state.bulb.serial_R);
      output->state.bulb.filament_temperature += dT < 1000.0f ? dT : 1000.0f; // Limit initial current surge (1ms is a bit long when emulating this part of the heating)
      core_eye_flicker_fusion(output, (float)bulb_filament_temperature_to_emission(output->state.bulb.filament_temperature));
      output->state.bulb.prevIntegrationTimestamp += dt;
    }
    output->state.bulb.prevIntegrationTimestamp = output->state.bulb.integrationTimestamp;
    output->state.bulb.prevIntegrationValue = U;
  }
  // else: wait with the integration until some more time vanished or the state will flip
  output->state.bulb.integrationTimestamp = now;
```

When integration is performed, you set the next integration value to be done on `U` starting from `output->state.bulb.integrationTimestamp`, but at this point `output->state.bulb.integrationTimestamp` is pointing to the previous integration timestamp while `U` value is valid starting from `now` timestamp. This does not seem correct to me.

**Comment by toxieainc** [comment]
Thanks, i will think through all that again, hopefully this evening.

**Comment by toxieainc** [comment]
..sorry, still on my todo-list to double check this.

But i guess what confused you, is the overall delay of the integration.
In order to collect and process (roughly) same-sized time intervals to not screw with the PWM 'conversion' quality, there is always a delay by buffering things.
Due to the regular triggering of the updates, this delay is not that bad in practice though and should not be noticeable.
I also double checked the output of the final results back then (numeric values), and this looked all sane.

But maybe i still missed something.. .. ..

**Comment by toxieainc** [comment]
..small update as i had some more time: I just double checked the implementation and the outputs again, all still looks fine to me with the current scheme

**Pull request closed without merging**
