### PR TITLE
fix static and DWORD to compile on Linux

### PR DESCRIPTION
**Pull request by stephenhouser**
Fix several `static` functions that were not static in their prototypes (this is an error on new `gcc`s)
Add missing `typedef` for `DWORD` in wpc.c as `DWORD` is a Windows thing (4 bytes).
These changes allow a minimally compile and working `xpinmame.x11` on Ubuntu test system.
Using gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0

### CODE REVIEW

**Comment by stephenhouser** [comment]
Earlier comment may have been misleading. The gcc version is 10.2 the Ubuntu version is 20.10. Arch Linux was "current" as of 2021/1/17.

**Comment by jsm174** [comment]
@stephenhouser - Hello. This repo is just a clone of svn, so issues and PRs here are not regularly watched. 

Coincidentally I was working on [libpinmame](https://github.com/VisualPinball/pinmame-dotnet) for OSX and had the same issues. They were addressed a few days ago: https://github.com/vpinball/pinmame/commit/da2f115adf68ded1c2a156efe20eb22d1edc6357

Can you try again with master?

**Comment by stephenhouser** [comment]
@jsm174 - so where would issues and PRs go? 

I posted over at VPForums (https://www.vpforums.org/index.php?showtopic=27063&page=60) and the response seemed to be that a PR/issue here was appropriate?

**Comment by jsm174** [comment]
Sorry this PR closed. When I forced pushed the repo with an updated authors list, GitHub automatically closed it.

There was talk on VPForums, this will now be the official repo for PinMAME!

**Comment by toxieainc** [comment]
All the changes from the PR were also merged to SVN, so are now also part of master

**Pull request closed without merging**
